WebDriverPhelps/Models/AcModel.cs
namespace WebDriverPhelps.Models
{
    public class AcModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

WebDriverPhelps/Models/ArModel.cs
using System.Security.Principal;

namespace WebDriverPhelps.Models
{
    public class ArModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string LinkAR { get; set; }
        public int? Ac_id { get; set; }
        
        







    }
}

WebDriverPhelps/Models/ErrorViewModel.cs
namespace WebDriverPhelps.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebDriverPhelps/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebDriverPhelps.Models;

namespace WebDriverPhelps.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebDriverPhelps/Controllers/RelatorioController.cs
using Microsoft.AspNetCore.Mvc;
using WebDriverPhelps.Repository;

namespace WebDriverPhelps.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly ISeleniumWeb _seleniumWeb;

        public RelatorioController(ISeleniumWeb seleniumWeb)
        {
            _seleniumWeb = seleniumWeb;
        }

        public IActionResult Index()
        {
            var ars = _seleniumWeb.BuscarTodos();
            return View(ars);
        }

        public IActionResult ExtrairPlanilha(int arId, DateTime dataini, DateTime datafim)
        {
            try
            {
                _seleniumWeb.ExtrairRelatorioIndividual(arId, dataini, datafim);
            }
            catch (Exception)
            {
            }

            return RedirectToAction("Index");
        }

        public IActionResult ExtrairPlanilhaPorAC(int arId, DateTime dataini, DateTime datafim)
        {
            try
            {
                _seleniumWeb.RelatorioCompletoPorAC(arId, dataini, datafim);
            }
            catch (Exception)
            {
            }

            return RedirectToAction("Index");
        }

    }
}

WebDriverPhelps/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebDriverPhelps/Views/Relatorio/Index.cshtml
@model IQueryable<ArModel>

<div class="margin-top-10 text-center">
    <br />
    <h2>Relatório de AR</h2>
    <br />

    <form class="margin-top-10">
        <div class="row">

            <div class="col-md-4">
                <label class="form-label"><b>Selecione a AR</b></label>
                <select class="form-control" name="arId">
                    @if (Model != null)
                    {
                        foreach (var ar in Model)
                        {
                            <option value="@ar.Id">@ar.Nome</option>
                        }
                    }
                </select>
            </div>
            <div class="col-md-4">
                <label class="form-label"><b>Data Inicial</b></label>
                <input name="dataini" type="date" class="form-control" required>
                @Html.ValidationMessage("dataini", "", new { @class = "text-danger" })
            </div>
            <div class="col-md-4">
                <label class="form-label"><b>Data Fim</b></label>
                <input name="datafim" type="date" class="form-control" required>
                @Html.ValidationMessage("datafim", "", new { @class = "text-danger" })
            </div>

            <div class="margin-top-10 mb-3">
                <button asp-controller="Relatorio" asp-action="ExtrairPlanilha" class="btn btn-primary bg-dark">Confirmar</button>
            </div>
        </div>
    </form>




    <div class="margin-top-30 text-center">
        <h2>Relatório Completo</h2>
        <br />

        <form class="margin-top-10">
            <div class="row">
                <div class="col-md-4">
                    <label class="form-label"><b>Selecione a AC</b></label>

                    <select class="form-control" name="arId">
                        <option value="1">Qualitycert Matriz</option>
                        <option value="2">AC Qualitycert</option>
                        <option value="3">Direta</option>
                    </select>
                </div>

                <div class="col-md-4">
                    <label class="form-label"><b>Data Inicial</b></label>
                    <input name="dataini" type="date" class="form-control" required>
                    @Html.ValidationMessage("dataini", "", new { @class = "text-danger" })
                </div>

                <div class="col-md-4">
                    <label class="form-label"><b>Data Fim</b></label>
                    <input name="datafim" type="date" class="form-control" required>
                    @Html.ValidationMessage("datafim", "", new { @class = "text-danger" })
                </div>

                <div class="margin-top-10 mb-3">
                    <button asp-controller="Relatorio" asp-action="ExtrairPlanilhaPorAC" class="btn btn-primary bg-dark">Confirmar</button>
                </div>
            </div>
        </form>


    </div>
</div>

WebDriverPhelps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebDriverPhelps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebDriverPhelps.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">WebDriverPhelps</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Relatorio" asp-action="Index"> <i class="bi bi-file-earmark-spreadsheet"> </i>Relatório</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2024 - WebDriverPhelps - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>